name: Release Packaging

on:
  push:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Load dotenv
        run: just ci-load-dotenv

      - name: Check
        run: just fmt

      - name: Ensure version is equal to tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          [ "${{ env.game_version }}" == "${{ env.BRANCH_NAME }}" ] || exit 2

  publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    needs: [check]

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Load dotenv
        run: just ci-load-dotenv

      - name: Publish
        run: just publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
